// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQzX2AuYvz_kzspf00RiVmbjWLTKw2LKQ',
    appId: '1:982989412521:web:33cde7291721b106cc31b8',
    messagingSenderId: '982989412521',
    projectId: 'fir-crud-e5b86',
    authDomain: 'fir-crud-e5b86.firebaseapp.com',
    storageBucket: 'fir-crud-e5b86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArvSKKOXnlfRXHrmKeteW1B-hzzikWflU',
    appId: '1:982989412521:android:ba45a0cb12e1da1dcc31b8',
    messagingSenderId: '982989412521',
    projectId: 'fir-crud-e5b86',
    storageBucket: 'fir-crud-e5b86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtxhXn6up3WHwB5WWJ43g8lDV2sw-Ip2U',
    appId: '1:982989412521:ios:e51dd814fb70e6c6cc31b8',
    messagingSenderId: '982989412521',
    projectId: 'fir-crud-e5b86',
    storageBucket: 'fir-crud-e5b86.firebasestorage.app',
    iosBundleId: 'com.ajmal.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtxhXn6up3WHwB5WWJ43g8lDV2sw-Ip2U',
    appId: '1:982989412521:ios:2e489742a9f8a4adcc31b8',
    messagingSenderId: '982989412521',
    projectId: 'fir-crud-e5b86',
    storageBucket: 'fir-crud-e5b86.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQzX2AuYvz_kzspf00RiVmbjWLTKw2LKQ',
    appId: '1:982989412521:web:1992a997e1d2f025cc31b8',
    messagingSenderId: '982989412521',
    projectId: 'fir-crud-e5b86',
    authDomain: 'fir-crud-e5b86.firebaseapp.com',
    storageBucket: 'fir-crud-e5b86.firebasestorage.app',
  );
}
